TRUNCATE HorseRaceDB.MASTER_COURSE;
ALTER TABLE HorseRaceDB.MASTER_COURSE auto_increment = 1;

INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('01','芝',1000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('01','芝',1200,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('01','芝',1500,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('01','芝',1800,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('01','芝',2000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('01','芝',2600,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('01','ダ',1000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('01','ダ',1700,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('01','ダ',2400,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('02','芝',1000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('02','芝',1200,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('02','芝',1700,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('02','芝',1800,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('02','芝',2000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('02','芝',2600,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('02','ダ',1000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('02','ダ',1700,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('02','ダ',2400,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','ダ',1000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','芝',1200,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','芝',1700,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','芝',1800,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','芝',2000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','芝',2600,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','ダ',1000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','ダ',1150,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','ダ',1700,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('03','ダ',2400,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',1000,'直',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',1200,'左','内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',1400,'左','内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',2000,'左','内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',2200,'左','内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',2400,'左','内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',1400,'左','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',1600,'左','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',1800,'左','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',2000,'左','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',3000,'左','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','芝',3200,'左','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','ダ',1000,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','ダ',1200,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','ダ',1700,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','ダ',1800,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','ダ',2500,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','障',2850,null,'芝 外-内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','障',3250,null,'芝 外-内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','障',2890,null,'芝 外-内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('04','障',3290,null,'芝 外-内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',1400,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',1600,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',1800,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',2000,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',2300,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',2400,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',2500,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',2600,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',3400,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','ダ',1200,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','ダ',1300,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','ダ',1400,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','ダ',1600,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','ダ',2100,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','ダ',2400,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',3110,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','芝',3300,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','障',3000,'左','芝 ダート',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','障',3100,'左','芝 ダート',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('05','障',3300,'左','芝 ダート',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',1200,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',1600,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',1800,'右','内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',2000,'右','内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',2200,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',2500,'右','内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',2600,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',3200,'右','外 内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',3600,'右','内',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','芝',4000,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','ダ',1000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','ダ',1200,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','ダ',1700,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','ダ',1800,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','ダ',2400,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','ダ',2500,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',2710,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',3030,'null','芝 外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',3210,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',3350,'null','芝 外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',3370,'null','芝 外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',3570,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',4100,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',4250,'null','芝 外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',4260,'null','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',2700,'null','芝 ダート',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',2880,'null','芝 ダート',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('06','障',3200,'null','芝 ダート',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','芝',1200,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','芝',1300,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','芝',1400,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','芝',1600,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','芝',2000,'左',null,'意外と福永さんの勝率が高くない');
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','芝',2200,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','芝',3000,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','ダ',1200,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','ダ',1400,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','ダ',1800,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','ダ',1900,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','ダ',2500,'左',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','障',3000,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','障',3300,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','障',3330,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','障',3600,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','障',3900,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('07','障',3940,'null','芝',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',1100,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',1200,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',1400,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',1400,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',1600,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',1600,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',1800,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',2000,'右',null,null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',2000,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',2200,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',2400,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',3000,'右','外',null);
INSERT INTO HorseRaceDB.MASTER_COURSE (course_placeid,course_turftype,course_distance,course_direction,course_inner,course_memo) VALUES('08','芝',3200,'右','外',null);
